### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Krilliac** [Damian666/Orion-Plus-Game-Engine#33]
9/2/2017 4:52:22 AM
System.Runtime.InteropServices.SEHException(0x80004005): External component has thrown an exception.
   at SFML.Graphics.Image.sfImage_createFromColor(UInt32 Width, UInt32 Height, Color Col)
   at SFML.Graphics.Image..ctor(UInt32 width, UInt32 height, Color color)
   at OrionClient.ClientGraphics.DrawMapTint() in D:\Orion-Plus-Game-Engine-master\Source\Client\Source\Modules\ClientGraphics.vb:line 2536
   at OrionClient.ClientGraphics.Render_Graphics() in D:\Orion-Plus-Game-Engine-master\Source\Client\Source\Modules\ClientGraphics.vb:line 2033
   at OrionClient.ClientGameLogic.GameLoop() in D:\Orion-Plus-Game-Engine-master\Source\Client\Source\Modules\ClientGameLogic.vb:line 310
   at OrionClient.ClientGeneral.Startup() in D:\Orion-Plus-Game-Engine-master\Source\Client\Source\Modules\ClientGeneral.vb:line 141
   at OrionClient.FrmMenu.Frmmenu_Load(Object sender, EventArgs e) in D:\Orion-Plus-Game-Engine-master\Source\Client\Source\Forms\frmMenu.vb:line 44
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Line:2536 Filename: ClientGraphics.vb
Line:2033 Filename: ClientGraphics.vb
Line:310 Filename: ClientGameLogic.vb
Line:141 Filename: ClientGeneral.vb
Line:44 Filename: frmMenu.vb

**Comment by Raven-Quest** [comment]
works fine for me O.o

http://www.ascensiongamedev.com/resources/filehost/f41a5d69d20f751a60b552b8892c02bc.png

**Comment by Krilliac** [comment]
Sorry, should of added more information, this crash seems to occur some what randomly, but i've seen it mostly crash when your walk around in the very bottom of the screen.. it's happened to me at least 5 or 6 times with the client running on an avg of 10 min.

**Comment by Raven-Quest** [comment]
yea you should have lolz

anyway, I "think" its a memory leak, try without map tint.

if that does not help, also turn off night effect.

that way we can pinpoint it.

**Comment by Krilliac** [comment]
I wrapped DrawMapTint around with some error handling and it at least doesn't crash anymore, but the error is still thrown.
`
    Public Sub DrawMapTint()

        If Map.HasMapTint = 0 Then Exit Sub

        Try
            MapTintSprite = New Sprite(New Texture(New SFML.Graphics.Image(GameWindow.Size.X, GameWindow.Size.Y, SFML.Graphics.Color.White)))
            MapTintSprite.Color = New SFML.Graphics.Color(CurrentTintR, CurrentTintG, CurrentTintB, CurrentTintA)
            MapTintSprite.TextureRect = New IntRect(0, 0, GameWindow.Size.X, GameWindow.Size.Y)

            MapTintSprite.Position = New Vector2f(0, 0)

            GameWindow.Draw(MapTintSprite)
        Catch ex As Exception
            MessageBox.Show("DrawMapTint Error")
        End Try

    End Sub`

**Comment by Krilliac** [comment]
I turned off map tinting/night effect, and it seems to be fine now.

**Comment by Raven-Quest** [comment]
great, a memory leak, totally not hard to debug... fml...

**Comment by Krilliac** [comment]
Well... hate to put more work on your shoulders.. but i got a server crash to :D

**Comment by Raven-Quest** [comment]
oh ffs xD

think I fixed the memory leak though, get latest push, and let me know...

**Comment by Krilliac** [comment]
I cant quite put my finger on it yet... but i don't think the client is correctly closing out when the server goes down or when you close it.. it gets kinda stuck.. i can't see in task manager or anywhere else, but it's running some where, and i cant compile the client because it is running.. i can easily switch what file VS compiles to.. but its kinda annoying.

**Comment by Krilliac** [comment]
That commit also seems to have fixed the issue.

**Comment by Raven-Quest** [comment]
good, and yea, sometimes client takes a while to close, no idea why.
closing this one :)
