### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Krilliac** [Damian666/Orion-Plus-Game-Engine#34]
System.NullReferenceException(0x80004003): Object reference not set to an instance of an object.
   at OrionServer.ServerPets.SendUpdatePlayerPet(Int32 Index, Boolean OwnerOnly) in D:\Orion-Plus-Game-Engine-master\Source\Server\Source\Modules\Objects\ServerPets.vb:line 289
   at OrionServer.ServerPets.ReCallPet(Int32 Index) in D:\Orion-Plus-Game-Engine-master\Source\Server\Source\Modules\Objects\ServerPets.vb:line 961
   at OrionServer.ServerPlayers.LeftGame(Int32 Index) in D:\Orion-Plus-Game-Engine-master\Source\Server\Source\Modules\Objects\ServerPlayers.vb:line 2923
   at OrionServer.ServerGeneral.DestroyServer() in D:\Orion-Plus-Game-Engine-master\Source\Server\Source\Modules\ServerGeneral.vb:line 286
   at OrionServer.ServerGeneral.ConsoleEventCallback(Int32 eventType) in D:\Orion-Plus-Game-Engine-master\Source\Server\Source\Modules\ServerGeneral.vb:line 258
Line:289 Filename: ServerPets.vb
Line:961 Filename: ServerPets.vb
Line:2923 Filename: ServerPlayers.vb
Line:286 Filename: ServerGeneral.vb
Line:258 Filename: ServerGeneral.vb

Seemed to have happened after using the console to type in commands, after a while the console wont allow anymore input? (Not entirely sure on this, was trying to type in commands and it wouldn't let me after a certain point) then IIRC, i may of accidentally mistype one of the commands, then switched back to the client, then server suddenly shit its self.

**Comment by Krilliac** [comment]
Also, it may be worth taking a look at my project to aid this project.

https://github.com/mangosvb/serverZero

It is a World of Warcraft Emulator written in VB.NET, I've been working on it for the past several years, but I've recently been trying to move on from WoW Emulation (10 years) and stumbled upon this project.

No doubt there will be chalk full of goodies in there to port over.

**Comment by Raven-Quest** [comment]
should be fixed
