### ISSUE TITLE
Another server crash

### ISSUE THREAD

**Issue by Krilliac** [Damian666/Orion-Plus-Game-Engine#35]
9/3/2017 9:11:30 PM
System.IndexOutOfRangeException(0x80131508): Index was outside the bounds of the array.
   at OrionServer.ServerConsole.HandleCommandKick(String Line, String Command, String[] Parts) in D:\Orion-Plus-Game-Engine-master\Source\Server\Source\Modules\ServerConsole.vb:line 157
   at OrionServer.ServerConsole.FireEvent(ConcurrentStack`1& handlers, String line, String command, String[] parts) in D:\Orion-Plus-Game-Engine-master\Source\Server\Source\Modules\ServerConsole.vb:line 73
   at OrionServer.ServerConsole.ParseCommand(String line) in D:\Orion-Plus-Game-Engine-master\Source\Server\Source\Modules\ServerConsole.vb:line 60
   at OrionServer.ServerConsole.ConsoleThread() in D:\Orion-Plus-Game-Engine-master\Source\Server\Source\Modules\ServerConsole.vb:line 36
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Line:157 Filename: ServerConsole.vb
Line:73 Filename: ServerConsole.vb
Line:60 Filename: ServerConsole.vb
Line:36 Filename: ServerConsole.vb

Happened after doing /kick without supplying a name (also happens on other commands to)

**Comment by Krilliac** [comment]
```
    Sub HandleCommandKick(ByVal Line As String, ByVal Command As String, ByVal Parts As String())

        Try
            Dim Name As String

            If Parts.Length < 1 Then Exit Sub

            Name = Parts(1)



            If Not FindPlayer(Name) > 0 Then Exit Sub


            AlertMsg(FindPlayer(Name), "You have been kicked by the server owner!")
            LeftGame(FindPlayer(Name))

        Catch ex As Exception
            TextAdd("You need to supply a name!")
        End Try

    End Sub
```

Fixed it, doesn't crash anymore and prints out a nice message telling you, what you did wrong.

**Comment by Krilliac** [comment]
Also, is there a way to make it so other users can connect to the server with the Editor? Been looking though it and it only seems to be connecting to local and i don't see any config options to set the IP/Port

**Comment by Raven-Quest** [comment]
that's because it uses the same options from the client lol

**Comment by Krilliac** [comment]
Oh, Lol
